---
- name: Using cli_command agnostic modules
  hosts: arista_switches
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  vars:
          ansible_ssh_pass: alta3

  tasks:
          - name: run multiple commands on remote nodes
            ansible.netcommon.cli_command:
                    command: "{{ item }}"
            loop:
                    - show interfaces
            register: results

          - name: return ONLY the switch IP address
            debug:
                    var: results.results[0].stdout_lines[2].split()[-1]
